### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by pascalberger** [ociaw/StatiqMermaid#1]
Thanks for providing this module. I tried it out on Windows, but had a few issues:

1. Default configuration where it wants to call `mmdc` does not work. When I pass `mmdc.cmd` it can call Mermaid CLI
2. Piping the input through STDIN does not work and starting the process fails with the following error:
   ```
   [INFO] Mermaid/Process » CacheDocuments » RenderMermaidSvg » Exception while generating SVG from mermaid definition: Mermaid returned non-zero exit code: 1
   
   Please specify input file: -i <input>
   ```

I tried with mermaid-cli 9.3.0

**Comment by ociaw** [comment]
1. It looks like ProcessLauncher already handles Windows-specific executable extensions, so I might just switch to using that. I initially avoided it since it doesn't have any way of redirecting standard input, but that seems to be a moot point since
2. I can't get mermaid CLI to accept anything from STDIN on Windows, even outside of Statiq. It looks like a bug in mermaid CLI, so I've created [an issue](https://github.com/mermaid-js/mermaid-cli/issues/468) for it. In the meantime I'll see about using temp files to pass in input data.

**Comment by ociaw** [comment]
Looks like the STDIN issue in mermaid-cli has been fixed: https://github.com/mermaid-js/mermaid-cli/pull/482

**Comment by ociaw** [comment]
Default mmdc path is `mmdc.cmd` on Windows in the lattest release, though I haven't tested on an actual Windows machine yet.

**Comment by ociaw** [comment]
I have verified that StatiqMermaid works on Windows.
